export default [
  'https://adaptive-throat.glitch.me',
  'https://aerial-lancer.glitch.me',
  'https://alder-wax.glitch.me',
  'https://amusing-macaw.glitch.me',
  'https://atlantic-mink.glitch.me',
  'https://brief-trowel.glitch.me',
  'https://button-match.glitch.me',
  'https://cat-magic.glitch.me',
  'https://conscious-cheek.glitch.me',
  'https://friendly-gaura.glitch.me',
  'https://heather-guardian.glitch.me',
  'https://lavender-flea.glitch.me',
  'https://lucky-lunge.glitch.me',
  'https://mighty-effect.glitch.me',
  'https://patch-crush.glitch.me',
  'https://substantial-knuckle.glitch.me',
  'https://trapezoidal-scorpion.glitch.me',
] as const
